'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type ActionListItemModelExtended, type ChActionListRenderCustomEvent } from "@genexus/chameleon-controls-library";
import { ChActionListRender as ChActionListRenderElement, defineCustomElement as defineChActionListRender } from "@genexus/chameleon-controls-library/dist/components/ch-action-list-render.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChActionListRenderEvents = {
    onSelectedItemsChange: EventName<ChActionListRenderCustomEvent<ActionListItemModelExtended[]>>,
    onItemClick: EventName<ChActionListRenderCustomEvent<ActionListItemModelExtended>>
};

const ChActionListRender: StencilReactComponent<ChActionListRenderElement, ChActionListRenderEvents> = /*@__PURE__*/ createComponent<ChActionListRenderElement, ChActionListRenderEvents>({
    tagName: 'ch-action-list-render',
    elementClass: ChActionListRenderElement,
    react: React,
    events: {
        onSelectedItemsChange: 'selectedItemsChange',
        onItemClick: 'itemClick'
    } as ChActionListRenderEvents,
    defineCustomElement: defineChActionListRender
});

export default ChActionListRender;
