'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type AccordionItemExpandedChangeEvent, type ChAccordionRenderCustomEvent } from "@genexus/chameleon-controls-library";
import { ChAccordionRender as ChAccordionRenderElement, defineCustomElement as defineChAccordionRender } from "@genexus/chameleon-controls-library/dist/components/ch-accordion-render.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChAccordionRenderEvents = { onExpandedChange: EventName<ChAccordionRenderCustomEvent<AccordionItemExpandedChangeEvent>> };

const ChAccordionRender: StencilReactComponent<ChAccordionRenderElement, ChAccordionRenderEvents> = /*@__PURE__*/ createComponent<ChAccordionRenderElement, ChAccordionRenderEvents>({
    tagName: 'ch-accordion-render',
    elementClass: ChAccordionRenderElement,
    react: React,
    events: { onExpandedChange: 'expandedChange' } as ChAccordionRenderEvents,
    defineCustomElement: defineChAccordionRender
});

export default ChAccordionRender;
