'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChBarcodeScanner as ChBarcodeScannerElement, defineCustomElement as defineChBarcodeScanner } from "@genexus/chameleon-controls-library/dist/components/ch-barcode-scanner.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChBarcodeScannerEvents = {
    onCameras: EventName<CustomEvent<string[]>>,
    onRead: EventName<CustomEvent<string>>
};

const ChBarcodeScanner: StencilReactComponent<ChBarcodeScannerElement, ChBarcodeScannerEvents> = /*@__PURE__*/ createComponent<ChBarcodeScannerElement, ChBarcodeScannerEvents>({
    tagName: 'ch-barcode-scanner',
    elementClass: ChBarcodeScannerElement,
    react: React,
    events: {
        onCameras: 'cameras',
        onRead: 'read'
    } as ChBarcodeScannerEvents,
    defineCustomElement: defineChBarcodeScanner
});

export default ChBarcodeScanner;
