'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChCheckbox as ChCheckboxElement, defineCustomElement as defineChCheckbox } from "@genexus/chameleon-controls-library/dist/components/ch-checkbox.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChCheckboxEvents = {
    onClick: EventName<CustomEvent<any>>,
    onInput: EventName<CustomEvent<any>>
};

const ChCheckbox: StencilReactComponent<ChCheckboxElement, ChCheckboxEvents> = /*@__PURE__*/ createComponent<ChCheckboxElement, ChCheckboxEvents>({
    tagName: 'ch-checkbox',
    elementClass: ChCheckboxElement,
    react: React,
    events: {
        onClick: 'click',
        onInput: 'input'
    } as ChCheckboxEvents,
    defineCustomElement: defineChCheckbox
});

export default ChCheckbox;
