'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChChat as ChChatElement, defineCustomElement as defineChChat } from "@genexus/chameleon-controls-library/dist/components/ch-chat.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChChatEvents = NonNullable<unknown>;

const ChChat: StencilReactComponent<ChChatElement, ChChatEvents> = /*@__PURE__*/ createComponent<ChChatElement, ChChatEvents>({
    tagName: 'ch-chat',
    elementClass: ChChatElement,
    react: React,
    events: {} as ChChatEvents,
    defineCustomElement: defineChChat
});

export default ChChat;
