'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChCode as ChCodeElement, defineCustomElement as defineChCode } from "@genexus/chameleon-controls-library/dist/components/ch-code.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChCodeEvents = NonNullable<unknown>;

const ChCode: StencilReactComponent<ChCodeElement, ChCodeEvents> = /*@__PURE__*/ createComponent<ChCodeElement, ChCodeEvents>({
    tagName: 'ch-code',
    elementClass: ChCodeElement,
    react: React,
    events: {} as ChCodeEvents,
    defineCustomElement: defineChCode
});

export default ChCode;
