'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChCodeDiffEditor as ChCodeDiffEditorElement, defineCustomElement as defineChCodeDiffEditor } from "@genexus/chameleon-controls-library/dist/components/ch-code-diff-editor.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChCodeDiffEditorEvents = NonNullable<unknown>;

const ChCodeDiffEditor: StencilReactComponent<ChCodeDiffEditorElement, ChCodeDiffEditorEvents> = /*@__PURE__*/ createComponent<ChCodeDiffEditorElement, ChCodeDiffEditorEvents>({
    tagName: 'ch-code-diff-editor',
    elementClass: ChCodeDiffEditorElement,
    react: React,
    events: {} as ChCodeDiffEditorEvents,
    defineCustomElement: defineChCodeDiffEditor
});

export default ChCodeDiffEditor;
