'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChComboBoxRender as ChComboBoxRenderElement, defineCustomElement as defineChComboBoxRender } from "@genexus/chameleon-controls-library/dist/components/ch-combo-box-render.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChComboBoxRenderEvents = {
    onFilterChange: EventName<CustomEvent<string>>,
    onInput: EventName<CustomEvent<string>>
};

const ChComboBoxRender: StencilReactComponent<ChComboBoxRenderElement, ChComboBoxRenderEvents> = /*@__PURE__*/ createComponent<ChComboBoxRenderElement, ChComboBoxRenderEvents>({
    tagName: 'ch-combo-box-render',
    elementClass: ChComboBoxRenderElement,
    react: React,
    events: {
        onFilterChange: 'filterChange',
        onInput: 'input'
    } as ChComboBoxRenderEvents,
    defineCustomElement: defineChComboBoxRender
});

export default ChComboBoxRender;
