'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChDialog as ChDialogElement, defineCustomElement as defineChDialog } from "@genexus/chameleon-controls-library/dist/components/ch-dialog.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChDialogEvents = { onDialogClosed: EventName<CustomEvent<any>> };

const ChDialog: StencilReactComponent<ChDialogElement, ChDialogEvents> = /*@__PURE__*/ createComponent<ChDialogElement, ChDialogEvents>({
    tagName: 'ch-dialog',
    elementClass: ChDialogElement,
    react: React,
    events: { onDialogClosed: 'dialogClosed' } as ChDialogEvents,
    defineCustomElement: defineChDialog
});

export default ChDialog;
