'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type ChEditCustomEvent } from "@genexus/chameleon-controls-library";
import { ChEdit as ChEditElement, defineCustomElement as defineChEdit } from "@genexus/chameleon-controls-library/dist/components/ch-edit.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChEditEvents = {
    onChange: EventName<CustomEvent<any>>,
    onInput: EventName<ChEditCustomEvent<InputEvent>>,
    onTriggerClick: EventName<CustomEvent<any>>
};

const ChEdit: StencilReactComponent<ChEditElement, ChEditEvents> = /*@__PURE__*/ createComponent<ChEditElement, ChEditEvents>({
    tagName: 'ch-edit',
    elementClass: ChEditElement,
    react: React,
    events: {
        onChange: 'change',
        onInput: 'input',
        onTriggerClick: 'triggerClick'
    } as ChEditEvents,
    defineCustomElement: defineChEdit
});

export default ChEdit;
