'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type ChFlexibleLayoutRenderCustomEvent, type FlexibleLayoutWidgetCloseInfo } from "@genexus/chameleon-controls-library";
import { ChFlexibleLayoutRender as ChFlexibleLayoutRenderElement, defineCustomElement as defineChFlexibleLayoutRender } from "@genexus/chameleon-controls-library/dist/components/ch-flexible-layout-render.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChFlexibleLayoutRenderEvents = { onWidgetClose: EventName<ChFlexibleLayoutRenderCustomEvent<FlexibleLayoutWidgetCloseInfo>> };

const ChFlexibleLayoutRender: StencilReactComponent<ChFlexibleLayoutRenderElement, ChFlexibleLayoutRenderEvents> = /*@__PURE__*/ createComponent<ChFlexibleLayoutRenderElement, ChFlexibleLayoutRenderEvents>({
    tagName: 'ch-flexible-layout-render',
    elementClass: ChFlexibleLayoutRenderElement,
    react: React,
    events: { onWidgetClose: 'widgetClose' } as ChFlexibleLayoutRenderEvents,
    defineCustomElement: defineChFlexibleLayoutRender
});

export default ChFlexibleLayoutRender;
