'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChImage as ChImageElement, defineCustomElement as defineChImage } from "@genexus/chameleon-controls-library/dist/components/ch-image.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChImageEvents = NonNullable<unknown>;

const ChImage: StencilReactComponent<ChImageElement, ChImageEvents> = /*@__PURE__*/ createComponent<ChImageElement, ChImageEvents>({
    tagName: 'ch-image',
    elementClass: ChImageElement,
    react: React,
    events: {} as ChImageEvents,
    defineCustomElement: defineChImage
});

export default ChImage;
