'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type ChIntersectionObserverCustomEvent } from "@genexus/chameleon-controls-library";
import { ChIntersectionObserver as ChIntersectionObserverElement, defineCustomElement as defineChIntersectionObserver } from "@genexus/chameleon-controls-library/dist/components/ch-intersection-observer.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChIntersectionObserverEvents = { onIntersectionUpdate: EventName<ChIntersectionObserverCustomEvent<IntersectionObserverEntry>> };

const ChIntersectionObserver: StencilReactComponent<ChIntersectionObserverElement, ChIntersectionObserverEvents> = /*@__PURE__*/ createComponent<ChIntersectionObserverElement, ChIntersectionObserverEvents>({
    tagName: 'ch-intersection-observer',
    elementClass: ChIntersectionObserverElement,
    react: React,
    events: { onIntersectionUpdate: 'intersectionUpdate' } as ChIntersectionObserverEvents,
    defineCustomElement: defineChIntersectionObserver
});

export default ChIntersectionObserver;
