'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChLayoutSplitter as ChLayoutSplitterElement, defineCustomElement as defineChLayoutSplitter } from "@genexus/chameleon-controls-library/dist/components/ch-layout-splitter.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChLayoutSplitterEvents = NonNullable<unknown>;

const ChLayoutSplitter: StencilReactComponent<ChLayoutSplitterElement, ChLayoutSplitterEvents> = /*@__PURE__*/ createComponent<ChLayoutSplitterElement, ChLayoutSplitterEvents>({
    tagName: 'ch-layout-splitter',
    elementClass: ChLayoutSplitterElement,
    react: React,
    events: {} as ChLayoutSplitterEvents,
    defineCustomElement: defineChLayoutSplitter
});

export default ChLayoutSplitter;
