'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChMarkdownViewer as ChMarkdownViewerElement, defineCustomElement as defineChMarkdownViewer } from "@genexus/chameleon-controls-library/dist/components/ch-markdown-viewer.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChMarkdownViewerEvents = NonNullable<unknown>;

const ChMarkdownViewer: StencilReactComponent<ChMarkdownViewerElement, ChMarkdownViewerEvents> = /*@__PURE__*/ createComponent<ChMarkdownViewerElement, ChMarkdownViewerEvents>({
    tagName: 'ch-markdown-viewer',
    elementClass: ChMarkdownViewerElement,
    react: React,
    events: {} as ChMarkdownViewerEvents,
    defineCustomElement: defineChMarkdownViewer
});

export default ChMarkdownViewer;
