'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type ChNavigationListRenderCustomEvent, type NavigationListHyperlinkClickEvent, type NavigationListItemModel } from "@genexus/chameleon-controls-library";
import { ChNavigationListRender as ChNavigationListRenderElement, defineCustomElement as defineChNavigationListRender } from "@genexus/chameleon-controls-library/dist/components/ch-navigation-list-render.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChNavigationListRenderEvents = {
    onButtonClick: EventName<ChNavigationListRenderCustomEvent<NavigationListItemModel>>,
    onHyperlinkClick: EventName<ChNavigationListRenderCustomEvent<NavigationListHyperlinkClickEvent>>
};

const ChNavigationListRender: StencilReactComponent<ChNavigationListRenderElement, ChNavigationListRenderEvents> = /*@__PURE__*/ createComponent<ChNavigationListRenderElement, ChNavigationListRenderEvents>({
    tagName: 'ch-navigation-list-render',
    elementClass: ChNavigationListRenderElement,
    react: React,
    events: {
        onButtonClick: 'buttonClick',
        onHyperlinkClick: 'hyperlinkClick'
    } as ChNavigationListRenderEvents,
    defineCustomElement: defineChNavigationListRender
});

export default ChNavigationListRender;
