'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type ChPaginatorPagesCustomEvent, type ChPaginatorPagesPageChangedEvent } from "@genexus/chameleon-controls-library";
import { ChPaginatorPages as ChPaginatorPagesElement, defineCustomElement as defineChPaginatorPages } from "@genexus/chameleon-controls-library/dist/components/ch-paginator-pages.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChPaginatorPagesEvents = { onPageChanged: EventName<ChPaginatorPagesCustomEvent<ChPaginatorPagesPageChangedEvent>> };

const ChPaginatorPages: StencilReactComponent<ChPaginatorPagesElement, ChPaginatorPagesEvents> = /*@__PURE__*/ createComponent<ChPaginatorPagesElement, ChPaginatorPagesEvents>({
    tagName: 'ch-paginator-pages',
    elementClass: ChPaginatorPagesElement,
    react: React,
    events: { onPageChanged: 'pageChanged' } as ChPaginatorPagesEvents,
    defineCustomElement: defineChPaginatorPages
});

export default ChPaginatorPages;
