'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type ChPaginatorNavigateClickedEvent, type ChPaginatorNavigateCustomEvent } from "@genexus/chameleon-controls-library";
import { ChPaginatorNavigate as ChPaginatorNavigateElement, defineCustomElement as defineChPaginatorNavigate } from "@genexus/chameleon-controls-library/dist/components/ch-paginator-navigate.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChPaginatorNavigateEvents = { onNavigateClicked: EventName<ChPaginatorNavigateCustomEvent<ChPaginatorNavigateClickedEvent>> };

const ChPaginatorNavigate: StencilReactComponent<ChPaginatorNavigateElement, ChPaginatorNavigateEvents> = /*@__PURE__*/ createComponent<ChPaginatorNavigateElement, ChPaginatorNavigateEvents>({
    tagName: 'ch-paginator-navigate',
    elementClass: ChPaginatorNavigateElement,
    react: React,
    events: { onNavigateClicked: 'navigateClicked' } as ChPaginatorNavigateEvents,
    defineCustomElement: defineChPaginatorNavigate
});

export default ChPaginatorNavigate;
