'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type ChPaginatorActivePageChangedEvent, type ChPaginatorCustomEvent, type ChPaginatorPageNavigationRequestedEvent } from "@genexus/chameleon-controls-library";
import { ChPaginator as ChPaginatorElement, defineCustomElement as defineChPaginator } from "@genexus/chameleon-controls-library/dist/components/ch-paginator.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChPaginatorEvents = {
    onActivePageChanged: EventName<ChPaginatorCustomEvent<ChPaginatorActivePageChangedEvent>>,
    onPageNavigationRequested: EventName<ChPaginatorCustomEvent<ChPaginatorPageNavigationRequestedEvent>>
};

const ChPaginator: StencilReactComponent<ChPaginatorElement, ChPaginatorEvents> = /*@__PURE__*/ createComponent<ChPaginatorElement, ChPaginatorEvents>({
    tagName: 'ch-paginator',
    elementClass: ChPaginatorElement,
    react: React,
    events: {
        onActivePageChanged: 'activePageChanged',
        onPageNavigationRequested: 'pageNavigationRequested'
    } as ChPaginatorEvents,
    defineCustomElement: defineChPaginator
});

export default ChPaginator;
