'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChQr as ChQrElement, defineCustomElement as defineChQr } from "@genexus/chameleon-controls-library/dist/components/ch-qr.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChQrEvents = NonNullable<unknown>;

const ChQr: StencilReactComponent<ChQrElement, ChQrEvents> = /*@__PURE__*/ createComponent<ChQrElement, ChQrEvents>({
    tagName: 'ch-qr',
    elementClass: ChQrElement,
    react: React,
    events: {} as ChQrEvents,
    defineCustomElement: defineChQr
});

export default ChQr;
