'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChRadioGroupRender as ChRadioGroupRenderElement, defineCustomElement as defineChRadioGroupRender } from "@genexus/chameleon-controls-library/dist/components/ch-radio-group-render.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChRadioGroupRenderEvents = { onChange: EventName<CustomEvent<string>> };

const ChRadioGroupRender: StencilReactComponent<ChRadioGroupRenderElement, ChRadioGroupRenderEvents> = /*@__PURE__*/ createComponent<ChRadioGroupRenderElement, ChRadioGroupRenderEvents>({
    tagName: 'ch-radio-group-render',
    elementClass: ChRadioGroupRenderElement,
    react: React,
    events: { onChange: 'change' } as ChRadioGroupRenderEvents,
    defineCustomElement: defineChRadioGroupRender
});

export default ChRadioGroupRender;
