'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChSegmentedControlRender as ChSegmentedControlRenderElement, defineCustomElement as defineChSegmentedControlRender } from "@genexus/chameleon-controls-library/dist/components/ch-segmented-control-render.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChSegmentedControlRenderEvents = { onSelectedItemChange: EventName<CustomEvent<string>> };

const ChSegmentedControlRender: StencilReactComponent<ChSegmentedControlRenderElement, ChSegmentedControlRenderEvents> = /*@__PURE__*/ createComponent<ChSegmentedControlRenderElement, ChSegmentedControlRenderEvents>({
    tagName: 'ch-segmented-control-render',
    elementClass: ChSegmentedControlRenderElement,
    react: React,
    events: { onSelectedItemChange: 'selectedItemChange' } as ChSegmentedControlRenderEvents,
    defineCustomElement: defineChSegmentedControlRender
});

export default ChSegmentedControlRender;
