'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChSidebar as ChSidebarElement, defineCustomElement as defineChSidebar } from "@genexus/chameleon-controls-library/dist/components/ch-sidebar.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChSidebarEvents = { onExpandedChange: EventName<CustomEvent<boolean>> };

const ChSidebar: StencilReactComponent<ChSidebarElement, ChSidebarEvents> = /*@__PURE__*/ createComponent<ChSidebarElement, ChSidebarEvents>({
    tagName: 'ch-sidebar',
    elementClass: ChSidebarElement,
    react: React,
    events: { onExpandedChange: 'expandedChange' } as ChSidebarEvents,
    defineCustomElement: defineChSidebar
});

export default ChSidebar;
