'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChSlider as ChSliderElement, defineCustomElement as defineChSlider } from "@genexus/chameleon-controls-library/dist/components/ch-slider.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChSliderEvents = {
    onChange: EventName<CustomEvent<number>>,
    onInput: EventName<CustomEvent<number>>
};

const ChSlider: StencilReactComponent<ChSliderElement, ChSliderEvents> = /*@__PURE__*/ createComponent<ChSliderElement, ChSliderEvents>({
    tagName: 'ch-slider',
    elementClass: ChSliderElement,
    react: React,
    events: {
        onChange: 'change',
        onInput: 'input'
    } as ChSliderEvents,
    defineCustomElement: defineChSlider
});

export default ChSlider;
