'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChSwitch as ChSwitchElement, defineCustomElement as defineChSwitch } from "@genexus/chameleon-controls-library/dist/components/ch-switch.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChSwitchEvents = { onInput: EventName<CustomEvent<any>> };

const ChSwitch: StencilReactComponent<ChSwitchElement, ChSwitchEvents> = /*@__PURE__*/ createComponent<ChSwitchElement, ChSwitchEvents>({
    tagName: 'ch-switch',
    elementClass: ChSwitchElement,
    react: React,
    events: { onInput: 'input' } as ChSwitchEvents,
    defineCustomElement: defineChSwitch
});

export default ChSwitch;
