'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChTabularGridVirtualScroller as ChTabularGridVirtualScrollerElement, defineCustomElement as defineChTabularGridVirtualScroller } from "@genexus/chameleon-controls-library/dist/components/ch-tabular-grid-virtual-scroller.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChTabularGridVirtualScrollerEvents = { onViewPortItemsChanged: EventName<CustomEvent<any>> };

const ChTabularGridVirtualScroller: StencilReactComponent<ChTabularGridVirtualScrollerElement, ChTabularGridVirtualScrollerEvents> = /*@__PURE__*/ createComponent<ChTabularGridVirtualScrollerElement, ChTabularGridVirtualScrollerEvents>({
    tagName: 'ch-tabular-grid-virtual-scroller',
    elementClass: ChTabularGridVirtualScrollerElement,
    react: React,
    events: { onViewPortItemsChanged: 'viewPortItemsChanged' } as ChTabularGridVirtualScrollerEvents,
    defineCustomElement: defineChTabularGridVirtualScroller
});

export default ChTabularGridVirtualScroller;
