'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type ChTabularGridColumnResizeCustomEvent, type TabularGridColumnResizeEvent } from "@genexus/chameleon-controls-library";
import { ChTabularGridColumnResize as ChTabularGridColumnResizeElement, defineCustomElement as defineChTabularGridColumnResize } from "@genexus/chameleon-controls-library/dist/components/ch-tabular-grid-column-resize.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChTabularGridColumnResizeEvents = {
    onColumnResizeStarted: EventName<ChTabularGridColumnResizeCustomEvent<TabularGridColumnResizeEvent>>,
    onColumnResizing: EventName<ChTabularGridColumnResizeCustomEvent<TabularGridColumnResizeEvent>>,
    onColumnResizeFinished: EventName<ChTabularGridColumnResizeCustomEvent<TabularGridColumnResizeEvent>>
};

const ChTabularGridColumnResize: StencilReactComponent<ChTabularGridColumnResizeElement, ChTabularGridColumnResizeEvents> = /*@__PURE__*/ createComponent<ChTabularGridColumnResizeElement, ChTabularGridColumnResizeEvents>({
    tagName: 'ch-tabular-grid-column-resize',
    elementClass: ChTabularGridColumnResizeElement,
    react: React,
    events: {
        onColumnResizeStarted: 'columnResizeStarted',
        onColumnResizing: 'columnResizing',
        onColumnResizeFinished: 'columnResizeFinished'
    } as ChTabularGridColumnResizeEvents,
    defineCustomElement: defineChTabularGridColumnResize
});

export default ChTabularGridColumnResize;
