'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChTabularGridActionbar as ChTabularGridActionbarElement, defineCustomElement as defineChTabularGridActionbar } from "@genexus/chameleon-controls-library/dist/components/ch-tabular-grid-actionbar.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChTabularGridActionbarEvents = NonNullable<unknown>;

const ChTabularGridActionbar: StencilReactComponent<ChTabularGridActionbarElement, ChTabularGridActionbarEvents> = /*@__PURE__*/ createComponent<ChTabularGridActionbarElement, ChTabularGridActionbarEvents>({
    tagName: 'ch-tabular-grid-actionbar',
    elementClass: ChTabularGridActionbarElement,
    react: React,
    events: {} as ChTabularGridActionbarEvents,
    defineCustomElement: defineChTabularGridActionbar
});

export default ChTabularGridActionbar;
