'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChTabularGridSettings as ChTabularGridSettingsElement, defineCustomElement as defineChTabularGridSettings } from "@genexus/chameleon-controls-library/dist/components/ch-tabular-grid-settings.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChTabularGridSettingsEvents = { onSettingsCloseClicked: EventName<CustomEvent<any>> };

const ChTabularGridSettings: StencilReactComponent<ChTabularGridSettingsElement, ChTabularGridSettingsEvents> = /*@__PURE__*/ createComponent<ChTabularGridSettingsElement, ChTabularGridSettingsEvents>({
    tagName: 'ch-tabular-grid-settings',
    elementClass: ChTabularGridSettingsElement,
    react: React,
    events: { onSettingsCloseClicked: 'settingsCloseClicked' } as ChTabularGridSettingsEvents,
    defineCustomElement: defineChTabularGridSettings
});

export default ChTabularGridSettings;
