'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChTabularGridRowsetEmpty as ChTabularGridRowsetEmptyElement, defineCustomElement as defineChTabularGridRowsetEmpty } from "@genexus/chameleon-controls-library/dist/components/ch-tabular-grid-rowset-empty.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChTabularGridRowsetEmptyEvents = NonNullable<unknown>;

const ChTabularGridRowsetEmpty: StencilReactComponent<ChTabularGridRowsetEmptyElement, ChTabularGridRowsetEmptyEvents> = /*@__PURE__*/ createComponent<ChTabularGridRowsetEmptyElement, ChTabularGridRowsetEmptyEvents>({
    tagName: 'ch-tabular-grid-rowset-empty',
    elementClass: ChTabularGridRowsetEmptyElement,
    react: React,
    events: {} as ChTabularGridRowsetEmptyEvents,
    defineCustomElement: defineChTabularGridRowsetEmpty
});

export default ChTabularGridRowsetEmpty;
