'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChTabularGridColumnDisplay as ChTabularGridColumnDisplayElement, defineCustomElement as defineChTabularGridColumnDisplay } from "@genexus/chameleon-controls-library/dist/components/ch-tabular-grid-column-display.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChTabularGridColumnDisplayEvents = NonNullable<unknown>;

const ChTabularGridColumnDisplay: StencilReactComponent<ChTabularGridColumnDisplayElement, ChTabularGridColumnDisplayEvents> = /*@__PURE__*/ createComponent<ChTabularGridColumnDisplayElement, ChTabularGridColumnDisplayEvents>({
    tagName: 'ch-tabular-grid-column-display',
    elementClass: ChTabularGridColumnDisplayElement,
    react: React,
    events: {} as ChTabularGridColumnDisplayEvents,
    defineCustomElement: defineChTabularGridColumnDisplay
});

export default ChTabularGridColumnDisplay;
