'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChTabularGridColumnSettings as ChTabularGridColumnSettingsElement, defineCustomElement as defineChTabularGridColumnSettings } from "@genexus/chameleon-controls-library/dist/components/ch-tabular-grid-column-settings.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChTabularGridColumnSettingsEvents = NonNullable<unknown>;

const ChTabularGridColumnSettings: StencilReactComponent<ChTabularGridColumnSettingsElement, ChTabularGridColumnSettingsEvents> = /*@__PURE__*/ createComponent<ChTabularGridColumnSettingsElement, ChTabularGridColumnSettingsEvents>({
    tagName: 'ch-tabular-grid-column-settings',
    elementClass: ChTabularGridColumnSettingsElement,
    react: React,
    events: {} as ChTabularGridColumnSettingsEvents,
    defineCustomElement: defineChTabularGridColumnSettings
});

export default ChTabularGridColumnSettings;
