'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type ChTabularGridCustomEvent, type TabularGridCellSelectionChangedEvent, type TabularGridMarkingChangedEvent, type TabularGridRowClickedEvent, type TabularGridRowContextMenuEvent, type TabularGridRowPressedEvent, type TabularGridSelectionChangedEvent } from "@genexus/chameleon-controls-library";
import { ChTabularGrid as ChTabularGridElement, defineCustomElement as defineChTabularGrid } from "@genexus/chameleon-controls-library/dist/components/ch-tabular-grid.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChTabularGridEvents = {
    onSelectionChanged: EventName<ChTabularGridCustomEvent<TabularGridSelectionChangedEvent>>,
    onRowMarkingChanged: EventName<ChTabularGridCustomEvent<TabularGridMarkingChangedEvent>>,
    onCellSelectionChanged: EventName<ChTabularGridCustomEvent<TabularGridCellSelectionChangedEvent>>,
    onRowClicked: EventName<ChTabularGridCustomEvent<TabularGridRowClickedEvent>>,
    onRowDoubleClicked: EventName<ChTabularGridCustomEvent<TabularGridRowClickedEvent>>,
    onRowEnterPressed: EventName<ChTabularGridCustomEvent<TabularGridRowPressedEvent>>,
    onRowContextMenu: EventName<ChTabularGridCustomEvent<TabularGridRowContextMenuEvent>>
};

const ChTabularGrid: StencilReactComponent<ChTabularGridElement, ChTabularGridEvents> = /*@__PURE__*/ createComponent<ChTabularGridElement, ChTabularGridEvents>({
    tagName: 'ch-tabular-grid',
    elementClass: ChTabularGridElement,
    react: React,
    events: {
        onSelectionChanged: 'selectionChanged',
        onRowMarkingChanged: 'rowMarkingChanged',
        onCellSelectionChanged: 'cellSelectionChanged',
        onRowClicked: 'rowClicked',
        onRowDoubleClicked: 'rowDoubleClicked',
        onRowEnterPressed: 'rowEnterPressed',
        onRowContextMenu: 'rowContextMenu'
    } as ChTabularGridEvents,
    defineCustomElement: defineChTabularGrid
});

export default ChTabularGrid;
