'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChTabularGridActionSettings as ChTabularGridActionSettingsElement, defineCustomElement as defineChTabularGridActionSettings } from "@genexus/chameleon-controls-library/dist/components/ch-tabular-grid-action-settings.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChTabularGridActionSettingsEvents = { onSettingsShowClicked: EventName<CustomEvent<any>> };

const ChTabularGridActionSettings: StencilReactComponent<ChTabularGridActionSettingsElement, ChTabularGridActionSettingsEvents> = /*@__PURE__*/ createComponent<ChTabularGridActionSettingsElement, ChTabularGridActionSettingsEvents>({
    tagName: 'ch-tabular-grid-action-settings',
    elementClass: ChTabularGridActionSettingsElement,
    react: React,
    events: { onSettingsShowClicked: 'settingsShowClicked' } as ChTabularGridActionSettingsEvents,
    defineCustomElement: defineChTabularGridActionSettings
});

export default ChTabularGridActionSettings;
