'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type ChTabularGridRowsetLegendCustomEvent } from "@genexus/chameleon-controls-library";
import { ChTabularGridRowsetLegend as ChTabularGridRowsetLegendElement, defineCustomElement as defineChTabularGridRowsetLegend } from "@genexus/chameleon-controls-library/dist/components/ch-tabular-grid-rowset-legend.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChTabularGridRowsetLegendEvents = { onRowsetLegendClicked: EventName<ChTabularGridRowsetLegendCustomEvent<CustomEvent>> };

const ChTabularGridRowsetLegend: StencilReactComponent<ChTabularGridRowsetLegendElement, ChTabularGridRowsetLegendEvents> = /*@__PURE__*/ createComponent<ChTabularGridRowsetLegendElement, ChTabularGridRowsetLegendEvents>({
    tagName: 'ch-tabular-grid-rowset-legend',
    elementClass: ChTabularGridRowsetLegendElement,
    react: React,
    events: { onRowsetLegendClicked: 'rowsetLegendClicked' } as ChTabularGridRowsetLegendEvents,
    defineCustomElement: defineChTabularGridRowsetLegend
});

export default ChTabularGridRowsetLegend;
