'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChTabularGridRender as ChTabularGridRenderElement, defineCustomElement as defineChTabularGridRender } from "@genexus/chameleon-controls-library/dist/components/ch-tabular-grid-render.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChTabularGridRenderEvents = NonNullable<unknown>;

const ChTabularGridRender: StencilReactComponent<ChTabularGridRenderElement, ChTabularGridRenderEvents> = /*@__PURE__*/ createComponent<ChTabularGridRenderElement, ChTabularGridRenderEvents>({
    tagName: 'ch-tabular-grid-render',
    elementClass: ChTabularGridRenderElement,
    react: React,
    events: {} as ChTabularGridRenderEvents,
    defineCustomElement: defineChTabularGridRender
});

export default ChTabularGridRender;
