'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChTabularGridActionRefresh as ChTabularGridActionRefreshElement, defineCustomElement as defineChTabularGridActionRefresh } from "@genexus/chameleon-controls-library/dist/components/ch-tabular-grid-action-refresh.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChTabularGridActionRefreshEvents = { onRefreshClicked: EventName<CustomEvent<any>> };

const ChTabularGridActionRefresh: StencilReactComponent<ChTabularGridActionRefreshElement, ChTabularGridActionRefreshEvents> = /*@__PURE__*/ createComponent<ChTabularGridActionRefreshElement, ChTabularGridActionRefreshEvents>({
    tagName: 'ch-tabular-grid-action-refresh',
    elementClass: ChTabularGridActionRefreshElement,
    react: React,
    events: { onRefreshClicked: 'refreshClicked' } as ChTabularGridActionRefreshEvents,
    defineCustomElement: defineChTabularGridActionRefresh
});

export default ChTabularGridActionRefresh;
