'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type ChTabRenderCustomEvent, type TabItemCloseInfo, type TabSelectedItemInfo } from "@genexus/chameleon-controls-library";
import { ChTabRender as ChTabRenderElement, defineCustomElement as defineChTabRender } from "@genexus/chameleon-controls-library/dist/components/ch-tab-render.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChTabRenderEvents = {
    onExpandMainGroup: EventName<CustomEvent<string>>,
    onItemClose: EventName<ChTabRenderCustomEvent<TabItemCloseInfo>>,
    onSelectedItemChange: EventName<ChTabRenderCustomEvent<TabSelectedItemInfo>>,
    onItemDragStart: EventName<CustomEvent<number>>
};

const ChTabRender: StencilReactComponent<ChTabRenderElement, ChTabRenderEvents> = /*@__PURE__*/ createComponent<ChTabRenderElement, ChTabRenderEvents>({
    tagName: 'ch-tab-render',
    elementClass: ChTabRenderElement,
    react: React,
    events: {
        onExpandMainGroup: 'expandMainGroup',
        onItemClose: 'itemClose',
        onSelectedItemChange: 'selectedItemChange',
        onItemDragStart: 'itemDragStart'
    } as ChTabRenderEvents,
    defineCustomElement: defineChTabRender
});

export default ChTabRender;
