'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChTabularGridRowActions as ChTabularGridRowActionsElement, defineCustomElement as defineChTabularGridRowActions } from "@genexus/chameleon-controls-library/dist/components/ch-tabular-grid-row-actions.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChTabularGridRowActionsEvents = { onRowActionOpened: EventName<CustomEvent<any>> };

const ChTabularGridRowActions: StencilReactComponent<ChTabularGridRowActionsElement, ChTabularGridRowActionsEvents> = /*@__PURE__*/ createComponent<ChTabularGridRowActionsElement, ChTabularGridRowActionsEvents>({
    tagName: 'ch-tabular-grid-row-actions',
    elementClass: ChTabularGridRowActionsElement,
    react: React,
    events: { onRowActionOpened: 'rowActionOpened' } as ChTabularGridRowActionsEvents,
    defineCustomElement: defineChTabularGridRowActions
});

export default ChTabularGridRowActions;
