'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChTabularGridColumnset as ChTabularGridColumnsetElement, defineCustomElement as defineChTabularGridColumnset } from "@genexus/chameleon-controls-library/dist/components/ch-tabular-grid-columnset.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChTabularGridColumnsetEvents = NonNullable<unknown>;

const ChTabularGridColumnset: StencilReactComponent<ChTabularGridColumnsetElement, ChTabularGridColumnsetEvents> = /*@__PURE__*/ createComponent<ChTabularGridColumnsetElement, ChTabularGridColumnsetEvents>({
    tagName: 'ch-tabular-grid-columnset',
    elementClass: ChTabularGridColumnsetElement,
    react: React,
    events: {} as ChTabularGridColumnsetEvents,
    defineCustomElement: defineChTabularGridColumnset
});

export default ChTabularGridColumnset;
