'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChTabularGridSettingsColumns as ChTabularGridSettingsColumnsElement, defineCustomElement as defineChTabularGridSettingsColumns } from "@genexus/chameleon-controls-library/dist/components/ch-tabular-grid-settings-columns.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChTabularGridSettingsColumnsEvents = NonNullable<unknown>;

const ChTabularGridSettingsColumns: StencilReactComponent<ChTabularGridSettingsColumnsElement, ChTabularGridSettingsColumnsEvents> = /*@__PURE__*/ createComponent<ChTabularGridSettingsColumnsElement, ChTabularGridSettingsColumnsEvents>({
    tagName: 'ch-tabular-grid-settings-columns',
    elementClass: ChTabularGridSettingsColumnsElement,
    react: React,
    events: {} as ChTabularGridSettingsColumnsEvents,
    defineCustomElement: defineChTabularGridSettingsColumns
});

export default ChTabularGridSettingsColumns;
