'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type ChTabularGridColumnCustomEvent, type TabularGridColumnDragEvent, type TabularGridColumnFreezeChangedEvent, type TabularGridColumnHiddenChangedEvent, type TabularGridColumnOrderChangedEvent, type TabularGridColumnSelectorClickedEvent, type TabularGridColumnSizeChangedEvent, type TabularGridColumnSortChangedEvent } from "@genexus/chameleon-controls-library";
import { ChTabularGridColumn as ChTabularGridColumnElement, defineCustomElement as defineChTabularGridColumn } from "@genexus/chameleon-controls-library/dist/components/ch-tabular-grid-column.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChTabularGridColumnEvents = {
    onColumnHiddenChanged: EventName<ChTabularGridColumnCustomEvent<TabularGridColumnHiddenChangedEvent>>,
    onColumnSizeChanging: EventName<ChTabularGridColumnCustomEvent<TabularGridColumnSizeChangedEvent>>,
    onColumnSizeChanged: EventName<ChTabularGridColumnCustomEvent<TabularGridColumnSizeChangedEvent>>,
    onColumnOrderChanged: EventName<ChTabularGridColumnCustomEvent<TabularGridColumnOrderChangedEvent>>,
    onColumnSortChanged: EventName<ChTabularGridColumnCustomEvent<TabularGridColumnSortChangedEvent>>,
    onColumnFreezeChanged: EventName<ChTabularGridColumnCustomEvent<TabularGridColumnFreezeChangedEvent>>,
    onColumnDragStarted: EventName<ChTabularGridColumnCustomEvent<TabularGridColumnDragEvent>>,
    onColumnDragging: EventName<ChTabularGridColumnCustomEvent<TabularGridColumnDragEvent>>,
    onColumnDragEnded: EventName<ChTabularGridColumnCustomEvent<TabularGridColumnDragEvent>>,
    onColumnSelectorClicked: EventName<ChTabularGridColumnCustomEvent<TabularGridColumnSelectorClickedEvent>>
};

const ChTabularGridColumn: StencilReactComponent<ChTabularGridColumnElement, ChTabularGridColumnEvents> = /*@__PURE__*/ createComponent<ChTabularGridColumnElement, ChTabularGridColumnEvents>({
    tagName: 'ch-tabular-grid-column',
    elementClass: ChTabularGridColumnElement,
    react: React,
    events: {
        onColumnHiddenChanged: 'columnHiddenChanged',
        onColumnSizeChanging: 'columnSizeChanging',
        onColumnSizeChanged: 'columnSizeChanged',
        onColumnOrderChanged: 'columnOrderChanged',
        onColumnSortChanged: 'columnSortChanged',
        onColumnFreezeChanged: 'columnFreezeChanged',
        onColumnDragStarted: 'columnDragStarted',
        onColumnDragging: 'columnDragging',
        onColumnDragEnded: 'columnDragEnded',
        onColumnSelectorClicked: 'columnSelectorClicked'
    } as ChTabularGridColumnEvents,
    defineCustomElement: defineChTabularGridColumn
});

export default ChTabularGridColumn;
