'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChTabularGridInfiniteScroll as ChTabularGridInfiniteScrollElement, defineCustomElement as defineChTabularGridInfiniteScroll } from "@genexus/chameleon-controls-library/dist/components/ch-tabular-grid-infinite-scroll.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChTabularGridInfiniteScrollEvents = { onInfinite: EventName<CustomEvent<any>> };

const ChTabularGridInfiniteScroll: StencilReactComponent<ChTabularGridInfiniteScrollElement, ChTabularGridInfiniteScrollEvents> = /*@__PURE__*/ createComponent<ChTabularGridInfiniteScrollElement, ChTabularGridInfiniteScrollEvents>({
    tagName: 'ch-tabular-grid-infinite-scroll',
    elementClass: ChTabularGridInfiniteScrollElement,
    react: React,
    events: { onInfinite: 'infinite' } as ChTabularGridInfiniteScrollEvents,
    defineCustomElement: defineChTabularGridInfiniteScroll
});

export default ChTabularGridInfiniteScroll;
