'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type ChThemeCustomEvent, type ChThemeLoadedEvent } from "@genexus/chameleon-controls-library";
import { ChTheme as ChThemeElement, defineCustomElement as defineChTheme } from "@genexus/chameleon-controls-library/dist/components/ch-theme.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChThemeEvents = { onThemeLoaded: EventName<ChThemeCustomEvent<ChThemeLoadedEvent>> };

const ChTheme: StencilReactComponent<ChThemeElement, ChThemeEvents> = /*@__PURE__*/ createComponent<ChThemeElement, ChThemeEvents>({
    tagName: 'ch-theme',
    elementClass: ChThemeElement,
    react: React,
    events: { onThemeLoaded: 'themeLoaded' } as ChThemeEvents,
    defineCustomElement: defineChTheme
});

export default ChTheme;
