'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ChTooltip as ChTooltipElement, defineCustomElement as defineChTooltip } from "@genexus/chameleon-controls-library/dist/components/ch-tooltip.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChTooltipEvents = NonNullable<unknown>;

const ChTooltip: StencilReactComponent<ChTooltipElement, ChTooltipEvents> = /*@__PURE__*/ createComponent<ChTooltipElement, ChTooltipEvents>({
    tagName: 'ch-tooltip',
    elementClass: ChTooltipElement,
    react: React,
    events: {} as ChTooltipEvents,
    defineCustomElement: defineChTooltip
});

export default ChTooltip;
