'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type ChTreeViewRenderCustomEvent, type TreeViewItemContextMenu, type TreeViewItemModelExtended, type TreeViewItemOpenReferenceInfo } from "@genexus/chameleon-controls-library";
import { ChTreeViewRender as ChTreeViewRenderElement, defineCustomElement as defineChTreeViewRender } from "@genexus/chameleon-controls-library/dist/components/ch-tree-view-render.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ChTreeViewRenderEvents = {
    onCheckedItemsChange: EventName<ChTreeViewRenderCustomEvent<Map<string, TreeViewItemModelExtended>>>,
    onItemContextmenu: EventName<ChTreeViewRenderCustomEvent<TreeViewItemContextMenu>>,
    onItemOpenReference: EventName<ChTreeViewRenderCustomEvent<TreeViewItemOpenReferenceInfo>>,
    onSelectedItemsChange: EventName<ChTreeViewRenderCustomEvent<TreeViewItemModelExtended[]>>
};

const ChTreeViewRender: StencilReactComponent<ChTreeViewRenderElement, ChTreeViewRenderEvents> = /*@__PURE__*/ createComponent<ChTreeViewRenderElement, ChTreeViewRenderEvents>({
    tagName: 'ch-tree-view-render',
    elementClass: ChTreeViewRenderElement,
    react: React,
    events: {
        onCheckedItemsChange: 'checkedItemsChange',
        onItemContextmenu: 'itemContextmenu',
        onItemOpenReference: 'itemOpenReference',
        onSelectedItemsChange: 'selectedItemsChange'
    } as ChTreeViewRenderEvents,
    defineCustomElement: defineChTreeViewRender
});

export default ChTreeViewRender;
